"""Generate a round concrete fire bowl, with lava rocks and fire, for the 3D view.

    .venv/bin/python tools/make_fire_bowl_model.py [OUTPUT_DIR]

Writes `fire_bowl.obj` + `.mtl` + a concrete texture into OUTPUT_DIR
(default: `models/Fire Bowl/`). The models folder is never committed, so
this script is the model's source: run it again on any machine.

Modelled on Rich's reference photo: a bowl that's a slice of a sphere —
3.5 ft across the rim, 16 in tall, curving in to a small flat base — with a
thick flat concrete lip, a bed of dark lava rocks (a few glowing embers)
just below it, and a ring of flames — warm yellow low down, amber, orange
tips. Light grey speckled concrete.
Built Y-up (the OBJ convention), in feet; the editor fits it to whatever
size the scene gives it.

Materials glow through their `Ka` (ambient) colour: VTK's OBJ importer
lights a material's ambient at full strength in that colour, so the flames
(Ka = their own colour) stay bright from every side, and the concrete and
rocks get a modest Ka so their shaded sides aren't black. Every face has
texture coordinates — VTK drops them for the whole file if any face lacks
them.
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

import numpy as np
from PIL import Image, ImageFilter

RIM_R = 1.75  # ft, outside radius at the rim
LIP_R = 1.47  # ft, inside edge of the flat lip
BASE_R = 0.9  # ft, the small flat base
HEIGHT = 1.33  # ft (16 in)
BED = HEIGHT - 0.22  # ft, the lava-rock bed just below the lip
SEGMENTS = 72

CONCRETE = (0.72, 0.72, 0.69)  # light grey, like the reference
ROCK = (0.16, 0.15, 0.14)
EMBER = (0.55, 0.20, 0.08)
FLAME = (0.95, 0.45, 0.10)  # orange tips
FLAME_MID = (1.0, 0.62, 0.18)  # amber
FLAME_CORE = (1.0, 0.78, 0.30)  # warm yellow low in the fire


class _Mesh:
    """OBJ builder. Points are (x, y, height) in plan terms, written Y-up
    as (x, height, -y)."""

    def __init__(self):
        self.v, self.vt, self.groups = [], [], []

    def vertex(self, x, y, h):
        self.v.append((x, h, -y))
        return len(self.v)

    def uv(self, u, w):
        self.vt.append((u, w))
        return len(self.vt)

    def group(self, material):
        self.groups.append((material, []))

    def face(self, vertices, uvs):
        self.groups[-1][1].append((vertices, uvs))

    def write(self, path: Path, mtl_name: str):
        lines = [f"# fire bowl — generated by tools/{Path(__file__).name}", f"mtllib {mtl_name}"]
        lines += [f"v {x:.4f} {y:.4f} {z:.4f}" for x, y, z in self.v]
        lines += [f"vt {u:.4f} {w:.4f}" for u, w in self.vt]
        for material, faces in self.groups:
            lines.append(f"usemtl {material}")
            lines += ["f " + " ".join(f"{a}/{b}" for a, b in zip(vs, uvs)) for vs, uvs in faces]
        path.write_text("\n".join(lines) + "\n")


def _revolve(mesh: _Mesh, profile, outward: bool = True, u_repeat: float = 6.0, flat: bool = False):
    """A surface of revolution from a profile of (radius, height) points,
    quads between neighbouring profile points round the full circle.
    `flat`: a horizontal ring (the lip) — texture mapped straight down,
    not round the side, or it smears into radial streaks."""
    rings = []
    for r, h in profile:
        ring = []
        for k in range(SEGMENTS + 1):  # +1: a seam column, so texture u runs 0..1 cleanly
            a = 2 * math.pi * k / SEGMENTS
            ring.append((mesh.vertex(r * math.cos(a), r * math.sin(a), h), k / SEGMENTS * u_repeat))
        rings.append((ring, h))
    for (lower, h0), (upper, h1) in zip(rings, rings[1:]):
        for k in range(SEGMENTS):
            (a, ua), (b, ub) = lower[k], lower[k + 1]
            (c, uc), (d, ud) = upper[k + 1], upper[k]
            verts = [a, b, c, d]
            if flat:
                uvs = [mesh.uv(*_planar(mesh.v[i - 1])) for i in verts]
            else:
                uvs = [mesh.uv(ua, h0 / HEIGHT), mesh.uv(ub, h0 / HEIGHT),
                       mesh.uv(uc, h1 / HEIGHT), mesh.uv(ud, h1 / HEIGHT)]
            if not outward:
                verts, uvs = verts[::-1], uvs[::-1]
            mesh.face(verts, uvs)


def _planar(vertex) -> tuple[float, float]:
    x, _, z = vertex  # written Y-up: plan (x, -y) are (x, z)
    return x / (2 * RIM_R) + 0.5, z / (2 * RIM_R) + 0.5


def _disk(mesh: _Mesh, radius: float, height: float, facing_up: bool):
    centre = mesh.vertex(0, 0, height)
    cuv = mesh.uv(0.5, 0.5)
    for k in range(SEGMENTS):
        a0, a1 = 2 * math.pi * k / SEGMENTS, 2 * math.pi * (k + 1) / SEGMENTS
        p0 = mesh.vertex(radius * math.cos(a0), radius * math.sin(a0), height)
        p1 = mesh.vertex(radius * math.cos(a1), radius * math.sin(a1), height)
        u0 = mesh.uv(0.5 + 0.5 * math.cos(a0), 0.5 + 0.5 * math.sin(a0))
        u1 = mesh.uv(0.5 + 0.5 * math.cos(a1), 0.5 + 0.5 * math.sin(a1))
        verts, uvs = [centre, p0, p1], [cuv, u0, u1]
        mesh.face(verts if facing_up else verts[::-1], uvs if facing_up else uvs[::-1])


def _bowl_profile(steps: int = 14):
    """The outside: a slice of a sphere through the base edge (radius BASE_R
    at height 0) and the rim (RIM_R at HEIGHT)."""
    centre_h = (RIM_R**2 + HEIGHT**2 - BASE_R**2) / (2 * HEIGHT)
    radius = math.hypot(BASE_R, centre_h)
    return [(math.sqrt(max(radius**2 - (h - centre_h) ** 2, 0)), h) for h in np.linspace(0, HEIGHT, steps)]


def _lump(mesh: _Mesh, rng, cx, cy, h, size):
    """One lava rock: a jittered octahedron."""
    tips = [(1, 0, 0), (-1, 0, 0), (0, 1, 0), (0, -1, 0), (0, 0, 0.8), (0, 0, -0.4)]
    ids = []
    for dx, dy, dz in tips:
        j = rng.uniform(0.7, 1.3, 3)
        ids.append(mesh.vertex(cx + dx * size * j[0], cy + dy * size * j[1], h + dz * size * j[2]))
    faces = [(0, 2, 4), (2, 1, 4), (1, 3, 4), (3, 0, 4), (2, 0, 5), (1, 2, 5), (3, 1, 5), (0, 3, 5)]
    for f in faces:
        mesh.face([ids[i] for i in f], [mesh.uv(0, 0), mesh.uv(1, 0), mesh.uv(0.5, 1)])


def _flame(mesh: _Mesh, rng, cx, cy, base_h, height, radius, lean, bands: dict):
    """A flame tongue: a tapered, slightly twisted spike — bright yellow low
    down, orange towards the tip, like the reference. `bands` maps each
    material to the faces it gets."""
    sides = 6
    levels = [0.0, 0.25, 0.55, 0.8, 1.0]
    widths = [0.95, 1.0, 0.75, 0.4, 0.0]
    twist = rng.uniform(-0.6, 0.6)
    rings = []
    for t, wdt in zip(levels, widths):
        ring = []
        for k in range(sides):
            a = 2 * math.pi * k / sides + twist * t
            r = radius * wdt * rng.uniform(0.85, 1.15)
            ring.append(mesh.vertex(cx + r * math.cos(a) + lean[0] * t * height,
                                    cy + r * math.sin(a) * 0.55 + lean[1] * t * height,
                                    base_h + t * height))
        rings.append(ring)
    for level, (lower, upper) in enumerate(zip(rings, rings[1:])):
        band = bands[("flame_core", "flame_mid", "flame_mid", "flame")[level]]  # yellow low, amber, orange tips
        for k in range(sides):
            a, b, c, d = lower[k], lower[(k + 1) % sides], upper[(k + 1) % sides], upper[k]
            band.append(([a, b, c, d], [mesh.uv(0, 0), mesh.uv(1, 0), mesh.uv(1, 1), mesh.uv(0, 1)]))


def _concrete_texture(path: Path, px: int = 256):
    rng = np.random.default_rng(4)
    base = np.ones((px, px, 3)) * np.array(CONCRETE) * 255
    speckle = rng.normal(0, 1, (px, px))
    mottle = np.asarray(Image.fromarray(np.uint8(np.clip(128 + rng.normal(0, 40, (px, px)), 0, 255)))
                        .filter(ImageFilter.GaussianBlur(10)), float) / 128 - 1
    img = base * (1 + 0.05 * speckle + 0.06 * mottle)[..., None]
    Image.fromarray(np.uint8(np.clip(img, 0, 255))).save(path)


def make_fire_bowl(out_dir: Path) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(21)
    mesh = _Mesh()

    mesh.group("concrete")
    _revolve(mesh, _bowl_profile())  # the outside curve
    _revolve(mesh, [(RIM_R, HEIGHT), (LIP_R, HEIGHT)], flat=True)  # the flat lip
    _revolve(mesh, [(LIP_R, HEIGHT), (LIP_R - 0.03, BED)], outward=False)  # the short inside wall
    _disk(mesh, BASE_R, 0.0, facing_up=False)  # the base

    mesh.group("lava_rock")
    _disk(mesh, LIP_R - 0.03, BED, facing_up=True)  # the rock bed
    for _ in range(90):
        r = (LIP_R - 0.15) * math.sqrt(rng.uniform(0, 1))
        a = rng.uniform(0, 2 * math.pi)
        _lump(mesh, rng, r * math.cos(a), r * math.sin(a), BED + 0.03, rng.uniform(0.07, 0.14))

    mesh.group("ember")  # a few glowing rocks under the flames
    for _ in range(14):
        r, a = rng.uniform(0.3, 0.9), rng.uniform(0, 2 * math.pi)
        _lump(mesh, rng, r * math.cos(a), r * math.sin(a), BED + 0.05, rng.uniform(0.05, 0.09))

    flames = []
    for k in range(16):  # a ring of flames, a few in the middle, varied like real fire
        a = 2 * math.pi * k / 16 + rng.uniform(-0.2, 0.2)
        r = rng.uniform(0.35, 0.85)
        flames.append((r * math.cos(a), r * math.sin(a), rng.uniform(0.5, 1.15), rng.uniform(0.13, 0.21)))
    flames += [(rng.uniform(-0.25, 0.25), rng.uniform(-0.25, 0.25), rng.uniform(1.0, 1.35), 0.2) for _ in range(4)]
    bands = {"flame_core": [], "flame_mid": [], "flame": []}
    for cx, cy, height, radius in flames:
        _flame(mesh, rng, cx, cy, BED + 0.05, height, radius, rng.uniform(-0.12, 0.12, 2), bands)
    for material, faces in bands.items():
        mesh.group(material)
        for verts, uvs in faces:
            mesh.face(verts, uvs)

    obj, mtl, tex = out_dir / "fire_bowl.obj", out_dir / "fire_bowl.mtl", out_dir / "concrete.png"
    _concrete_texture(tex)
    mesh.write(obj, mtl.name)

    def material(name, kd, ka, texture=None):
        lines = [f"newmtl {name}", "Kd " + " ".join(f"{c:.3f}" for c in kd), "Ka " + " ".join(f"{c:.3f}" for c in ka)]
        if texture:
            lines.append(f"map_Kd {texture}")
        return "\n".join(lines) + "\n\n"

    mtl.write_text(
        "# fire bowl materials — Ka is how brightly each glows (see the module docstring)\n"
        + material("concrete", CONCRETE, [c * 0.62 for c in CONCRETE], tex.name)
        + material("lava_rock", ROCK, [c * 0.6 for c in ROCK])
        + material("ember", EMBER, EMBER)
        + material("flame", [c * 0.3 for c in FLAME], FLAME)
        + material("flame_mid", [c * 0.3 for c in FLAME_MID], FLAME_MID)
        + material("flame_core", [c * 0.3 for c in FLAME_CORE], FLAME_CORE)
    )
    return obj


if __name__ == "__main__":
    default = Path(__file__).resolve().parents[1] / "models" / "Fire Bowl"
    path = make_fire_bowl(Path(sys.argv[1]) if len(sys.argv) > 1 else default)
    print(f"wrote {path}")
