"""Generate a simple hot tub model for the 3D view (M11).

    .venv/bin/python tools/make_hot_tub_model.py [OUTPUT_DIR]

Writes `simple_hot_tub.obj` + `.mtl` + a plank texture into OUTPUT_DIR
(default: `models/Simple Hot Tub/`). The models folder is never committed,
so this script is the tub's source: run it again on any machine.

The tub: a 7 x 7 ft rounded square (1 ft corner radius), 3 ft tall — the
backyard's hot tub. Wooden plank exterior (sides and base); an off-white
acrylic shell inside with very little detail: the rim, the inner walls and
the floor. Built Y-up, the usual OBJ convention (the editor stands Y-up
models upright), in feet — though the editor fits a model to whatever size
the scene gives it anyway.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import shapely
from PIL import Image, ImageDraw, ImageFilter
from shapely.geometry import box

SIZE = 7.0  # ft, outside
CORNER_R = 1.0  # ft
HEIGHT = 3.0  # ft
RIM = 0.5  # ft, width of the acrylic lip
FLOOR = 0.4  # ft, height of the inside floor above the base
PLANK = 0.45  # ft, width of one exterior plank

WOOD = (0.55, 0.38, 0.25)  # warm cedar brown
SHELL = (0.93, 0.92, 0.88)  # off-white acrylic


def _rounded_square(size: float, radius: float):
    half = size / 2 - radius
    return box(-half, -half, half, half).buffer(radius, quad_segs=8)


def _ring(poly) -> np.ndarray:
    """The outline, counter-clockwise, without the repeated closing point."""
    return np.asarray(shapely.geometry.polygon.orient(poly, 1.0).exterior.coords)[:-1]


class _Mesh:
    """OBJ builder: vertices are plan (x, y) + height, written Y-up as
    (x, height, -y) so north stays north once stood upright."""

    def __init__(self):
        self.v, self.vt, self.groups = [], [], []

    def vertex(self, x, y, h) -> int:
        self.v.append((x, h, -y))
        return len(self.v)

    def uv(self, u, w) -> int:
        self.vt.append((u, w))
        return len(self.vt)

    def group(self, name: str, material: str):
        self.groups.append((name, material, []))

    def face(self, vertices, uvs=None):
        self.groups[-1][2].append((vertices, uvs))

    def write(self, path: Path, mtl_name: str):
        lines = [f"# simple hot tub — generated by tools/{Path(__file__).name}", f"mtllib {mtl_name}"]
        lines += [f"v {x:.4f} {y:.4f} {z:.4f}" for x, y, z in self.v]
        lines += [f"vt {u:.4f} {w:.4f}" for u, w in self.vt]
        for name, material, faces in self.groups:
            lines += [f"g {name}", f"usemtl {material}"]
            for verts, uvs in faces:
                if uvs:
                    lines.append("f " + " ".join(f"{a}/{b}" for a, b in zip(verts, uvs)))
                else:
                    lines.append("f " + " ".join(str(a) for a in verts))
        path.write_text("\n".join(lines) + "\n")


def _walls(mesh: _Mesh, ring: np.ndarray, bottom: float, top: float, facing_out: bool, textured: bool = True):
    """Vertical walls round `ring`; texture u runs along the perimeter in
    planks, v up the height.

    *Every* face in the file gets texture coordinates, even the untextured
    off-white shell: VTK's OBJ importer drops texture coordinates for the
    whole file if any face lacks them — a real bug here, the wood planks
    came out plain brown."""
    along = 0.0
    n = len(ring)
    for i in range(n):
        (x0, y0), (x1, y1) = ring[i], ring[(i + 1) % n]
        seg = float(np.hypot(x1 - x0, y1 - y0))
        a, b = mesh.vertex(x0, y0, bottom), mesh.vertex(x1, y1, bottom)
        c, d = mesh.vertex(x1, y1, top), mesh.vertex(x0, y0, top)
        verts = [a, b, c, d] if facing_out else [a, d, c, b]
        uvs = None
        if textured:
            u0, u1 = along / PLANK / 8, (along + seg) / PLANK / 8  # the texture holds 8 planks
            ua, ub = mesh.uv(u0, bottom / HEIGHT), mesh.uv(u1, bottom / HEIGHT)
            uc, ud = mesh.uv(u1, top / HEIGHT), mesh.uv(u0, top / HEIGHT)
            uvs = [ua, ub, uc, ud] if facing_out else [ua, ud, uc, ub]
        mesh.face(verts, uvs)
        along += seg


def _cap(mesh: _Mesh, region, height: float, facing_up: bool, textured: bool = True):
    """A flat horizontal face over `region` (holes allowed), triangulated,
    with planar texture coordinates."""
    for tri in shapely.constrained_delaunay_triangles(region).geoms:
        pts = np.asarray(shapely.geometry.polygon.orient(tri, 1.0).exterior.coords)[:3]
        ids = [mesh.vertex(x, y, height) for x, y in pts]
        uvs = [mesh.uv(x / SIZE + 0.5, y / SIZE + 0.5) for x, y in pts] if textured else None
        if facing_up:
            mesh.face(ids, uvs)
        else:
            mesh.face(ids[::-1], uvs[::-1] if uvs else None)


def _plank_texture(path: Path, px: int = 512):
    """Eight vertical cedar planks with a little grain and dark seams."""
    rng = np.random.default_rng(3)
    img = Image.new("RGB", (px, px))
    draw = ImageDraw.Draw(img)
    plank_px = px // 8
    for k in range(8):
        tone = np.array(WOOD) * rng.uniform(0.88, 1.1)
        draw.rectangle([k * plank_px, 0, (k + 1) * plank_px, px], fill=tuple(int(c * 255) for c in np.clip(tone, 0, 1)))
    grain = rng.normal(0, 1, (px, px // 4))
    grain = np.repeat(grain, 4, axis=1)  # streaks run along the plank (vertically after the blur)
    streaks = Image.fromarray(np.uint8(np.clip(128 + grain * 18, 0, 255))).filter(ImageFilter.GaussianBlur((1, 12)))
    base = np.asarray(img, float) * (0.9 + 0.2 * np.asarray(streaks, float)[..., None] / 255)
    img = Image.fromarray(np.uint8(np.clip(base, 0, 255)))
    draw = ImageDraw.Draw(img)
    for k in range(9):
        draw.line([(k * plank_px, 0), (k * plank_px, px)], fill=(70, 45, 30), width=3)
    img.save(path)


def make_hot_tub(out_dir: Path) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    outer = _rounded_square(SIZE, CORNER_R)
    inner = _rounded_square(SIZE - 2 * RIM, max(CORNER_R - RIM * 0.6, 0.3))
    mesh = _Mesh()

    mesh.group("exterior", "wood")
    _walls(mesh, _ring(outer), 0.0, HEIGHT, facing_out=True, textured=True)
    _cap(mesh, outer, 0.0, facing_up=False)  # the base

    mesh.group("shell", "acrylic")
    _cap(mesh, outer.difference(inner), HEIGHT, facing_up=True)  # the rim
    _walls(mesh, _ring(inner), FLOOR, HEIGHT, facing_out=False)  # inner walls face in
    _cap(mesh, inner, FLOOR, facing_up=True)  # the floor

    obj, mtl, tex = out_dir / "simple_hot_tub.obj", out_dir / "simple_hot_tub.mtl", out_dir / "wood_planks.png"
    _plank_texture(tex)
    mesh.write(obj, mtl.name)
    mtl.write_text(
        "# simple hot tub materials\n"
        f"newmtl wood\nKd {WOOD[0]} {WOOD[1]} {WOOD[2]}\nKa 0.2 0.2 0.2\nmap_Kd {tex.name}\n\n"
        f"newmtl acrylic\nKd {SHELL[0]} {SHELL[1]} {SHELL[2]}\nKa 0.2 0.2 0.2\n"
    )
    return obj


if __name__ == "__main__":
    default = Path(__file__).resolve().parents[1] / "models" / "Simple Hot Tub"
    path = make_hot_tub(Path(sys.argv[1]) if len(sys.argv) > 1 else default)
    print(f"wrote {path}")
